server:
  port: "${SERVER_PORT}"
  debug: ${SERVER_DEBUG}

rate_limit:
  shorten:
    count: ${RATE_LIMIT_SHORTEN_COUNT}
    period: "${RATE_LIMIT_SHORTEN_PERIOD}"
  redirect:
    count: ${RATE_LIMIT_REDIRECT_COUNT}
    period: "${RATE_LIMIT_REDIRECT_PERIOD}"

persistent_redis:
  addr: "${PERSISTENT_REDIS_ADDR}"
  redis_key_ids: "${PERSISTENT_REDIS_KEY}"

volatile_redis:
  addr: "${VOLATILE_REDIS_ADDR}"

dynamodb:
  region: "${AWS_REGION}"
  table_name: "${TABLE_NAME}"
  columns:
    id: "${DYNAMODB_COL_ID}"
    url: "${DYNAMODB_COL_URL}"

postgres:
  host: "${PG_HOST}"
  port: 5432
  user: "${PG_USER}"
  password: "${PG_PASSWORD}"
  name: "${PG_DATABASE}"
  table: "${PG_TABLE}"
  columns:
    id: "${PG_COL_ID}"
    url: "${PG_COL_URL}"

buffer:
  buffer_id_size: ${BUFFER_ID_SIZE}
  max_retries: ${BUFFER_MAX_RETRIES}

worker:
  idle_interval: "${WORKER_IDLE_INTERVAL}"
  pull_limit: ${WORKER_PULL_LIMIT}

cache:
  max_weight: ${CACHE_MAX_WEIGHT}
  expiry: "${CACHE_EXPIRY}"
